---
title: "depth_wrangling"
author: "Elke Windschitl"
date: "2023-02-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(raster)
library(sf)
library(terra)
library(tmap)
library(RColorBrewer)
```

```{r}
# # Make an empty raster of 0.008 degree resolution
# x <- rast() # make an empty raster
# x
# 
# crs(x) <- "EPSG:4326" # confirm WGS84
# crs(x)
# ext(x) <- c(-120.5, -119.45, 33.83, 34.49) # set extent
# ext(x)
# res(x) <- c(0.008, 0.008) # set resolution
# res(x)
# 
# nrow(x) # identify how many rows we have
# ncol(x) # identify how many columns we have
# ncell(x) # identify how many total cells we have
# values(x) <- 1:ncell(x) # fill in values 1-10873 by row
# 
# tmap_mode("view")
# tm_shape(x) +
#   tm_raster(style = "cont",
#             breaks = seq(0, ncell(x), by = 1000),
#             title = "Cell ID",
#             palette = "RdPu")
# 
# mask <- x
```

```{r}
# Read in mask
mask <- terra::rast("mask_rast.tif")
plot(mask)
```

```{r}
# Read in depth data
depth_dat <- terra::rast("/Users/elkewindschitl/Documents/MEDS/kelpGeoMod/data/depth/depth_long.tiff")

tm_shape(depth_dat) + # check the location
  tm_raster(style = "cont",
            breaks = seq(-2000, 1500, by = 100),
            title = "depth",
            palette = "-BrBG") 

# Read in Geoid tiles for depth correction
geoid1 <- terra::rast("/Users/elkewindschitl/Documents/MEDS/kelpGeoMod/data/depth/ETOPO_2022_v1_15s_N45W135_geoid.tif") # left tile

tm_shape(geoid1) + # check the location
  tm_raster(style = "cont",
            breaks = seq(-50, 50, by = 10),
            title = "Geoid Value",
            palette = "PRGn") 

geoid2 <- terra::rast("/Users/elkewindschitl/Documents/MEDS/kelpGeoMod/data/depth/ETOPO_2022_v1_15s_N45W120_geoid.tif") # right tile

tm_shape(geoid2) + # check the location
  tm_raster(style = "cont",
            breaks = seq(-50, 50, by = 10),
            title = "Geoid Value",
            palette = "PRGn") 

geoid_tile <- merge(geoid1, geoid2) # merge the tiles

tm_shape(geoid_tile) + # check the location
  tm_raster(style = "cont",
            breaks = seq(-50, 50, by = 10),
            title = "Geoid Value",
            palette = "PRGn")

# Crop geoid tile to match depth extent
geoid_tile <- crop(x = geoid_tile,
     y = depth_dat)

tm_shape(geoid_tile) + # check the location
  tm_raster(style = "cont",
            breaks = seq(-50, 50, by = 10),
            title = "Geoid Value",
            palette = "PRGn")

# Add the tiles together as per the user guide instructions (https://www.ngdc.noaa.gov/mgg/global/relief/ETOPO2022/docs/1.2%20ETOPO%202022%20User%20Guide.pdf)
depth_wgs84 <- depth_dat + geoid_tile
  
tm_shape(depth_wgs84) + # check the location
  tm_raster(style = "cont",
            breaks = seq(-2000, 1500, by = 100),
            title = "Geoid Value",
            palette = "-BrBG") 
```

```{r}
# Set CRS
crs(depth_wgs84) <- crs(mask) # set crs to mask crs
crs(depth_wgs84) # check crs
# Crop to mask
depth_wgs84 <- crop(x = depth_wgs84,
                         y = mask) # crop to set extent to mask extent
#ext(depth_wgs84)
# Resample to courser resolution
resampled_depth <- terra::resample(x = depth_wgs84,
                                   y = mask,
                                   method = "bilinear")

# mask to remove land
resampled_depth <- mask(resampled_depth, mask)
plot(resampled_depth)

# Confirm integrity of raster
crs(resampled_depth)
ext(resampled_depth)
res(resampled_depth)
nrow(resampled_depth)
ncol(resampled_depth)
plot(resampled_depth)

tm_shape(resampled_depth) + # check the location
  tm_raster(style = "cont",
            breaks = seq(-2000, 1500, by = 100),
            title = "Geoid Value",
            palette = "-BrBG")
plot(resampled_depth)
```

```{r}
terra::writeRaster(resampled_depth, "/Users/elkewindschitl/Documents/MEDS/kelpGeoMod/data/depth/SBC_depth.tif", filetype = "GTiff", overwrite = TRUE)
```

```{r}
boundaries <- st_read("/Users/elkewindschitl/Downloads/California_County_Boundaries/cnty19_1.shp") 

boundaries <- st_transform(x = boundaries, crs = 4326)

tmap_mode("view")
tm_shape(resampled_depth) + # check the location
  tm_raster(style = "cont",
            breaks = c(-2000, -1000, -500, -200, -100, -60, -40, -20, 0),
            title = "Depth (m)",
            palette = "Blues") +
  tm_layout(legend.outside = TRUE, # Moving the legend
            main.title = "Bathymetry of the Santa Barbara Channel",
            main.title.size = 0.8) +
  tm_shape(boundaries) +
  tm_polygons() +
  tm_grid(x = c(-120.4, -120.2, -120, -119.8, -119.6),
          y = c(34.0, 34.2, 34.4),
    alpha = 0.3) 
```


